### ISSUE TITLE
(1) Live Testing / Watcher [1]

### ISSUE THREAD

**Issue by trust2065** [efcsydney/efcsydney-roster#356]
#### User Story
As a developer, I would like to run the test cases automatically after save, 
And for the best we hope we can abort the test when we need and restart it,
so that we don't need to wait for it complete for next test modification or manually restart the test. 

#### Acceptance Criteria

- [x] Study to make sure watcher is one of the feature of Test Cafe
- [ ] Ensure that test case run automatically after save
- [ ] Ensure we are able to see the test result after save

**Comment by trust2065** [comment]
@josephj Can you have a look to make sure this is what we need?

ref: https://github.com/DevExpress/testcafe-live

change your focus on terminal then you can
ctrl+s - stop current test run;
ctrl+r - restart current test run;
ctrl+w - turn off/on files watching;
ctrl+c - close opened browsers and terminate the process.

I've add it on branch #356 base on #341 , 
run yarn test:functional-f-live to see

**Comment by josephj** [comment]
@trust2065 

Yep, I have tried. This is the watcher I meant. Whenever we update the test fixtures, it will re-run automatically. It's even more powerful than what I expected since we have more control.

For the `yarn test:functional-f-live` it's not straight-forward. Maybe we should use something like the following?

* `yarn testcafe` (`yarn testcafe:chrome-headless`)
* `yarn testcafe:chrome`
* `yarn testcafe:chrome-headless`
* `yarn testcafe-live` (`yarn testcafe-live:chrome`)
* `yarn testcafe-live:chrome`
* `yarn testcafe-live:chrome-headless`

Or maybe we should wait @waguei-andrea to implement the cli prompting task?

**Comment by josephj** [comment]
@trust2065 Got you! Don't forget to move the ticket to Done after you merge its pull request to master  😎
